import type { PoFile } from '@po-ai-editor/shared';

export const testPoFile: PoFile = {
  filename: 'messages.po',
  metadata: {
    projectVersion: '1.0.0',
    reportMsgidBugsTo: 'bugs@example.com',
    potCreationDate: '2026-06-10 12:00+0000',
    poRevisionDate: '2026-06-11 12:00+0000',
    lastTranslator: 'Jane Translator',
    languageTeam: 'German Team',
    language: 'English',
    contentType: 'text/plain; charset=UTF-8',
    contentTransferEncoding: '8bit',
    pluralForms: 'nplurals=2; plural=(n != 1);',
  },
  entries: [
    {
      id: 'entry-welcome',
      msgctxt: 'dashboard',
      msgid: 'Welcome back',
      msgidPlural: null,
      msgstr: '',
      msgstrPlural: [],
      comments: {
        translator: 'Homepage heading',
      },
      isFuzzy: false,
      isObsolete: false,
      isTranslated: false,
    },
    {
      id: 'entry-save',
      msgctxt: null,
      msgid: 'Save changes',
      msgidPlural: null,
      msgstr: 'Aenderungen speichern',
      msgstrPlural: [],
      comments: {
        translator: 'CTA label',
        extracted: 'Primary button',
        reference: 'src/components/save.tsx:12',
      },
      isFuzzy: false,
      isObsolete: false,
      isTranslated: true,
    },
    {
      id: 'entry-archive',
      msgctxt: null,
      msgid: 'Archive project',
      msgidPlural: null,
      msgstr: 'Projekt archivieren',
      msgstrPlural: [],
      comments: {
        reference: 'src/pages/project.tsx:88',
      },
      isFuzzy: true,
      isObsolete: false,
      isTranslated: true,
    },
    {
      id: 'entry-files',
      msgctxt: 'upload',
      msgid: 'File',
      msgidPlural: 'Files',
      msgstr: '',
      msgstrPlural: ['', ''],
      comments: {},
      isFuzzy: false,
      isObsolete: false,
      isTranslated: false,
    },
    {
      id: 'entry-legacy',
      msgctxt: null,
      msgid: 'Legacy copy',
      msgidPlural: null,
      msgstr: 'Veraltete Kopie',
      msgstrPlural: [],
      comments: {},
      isFuzzy: false,
      isObsolete: true,
      isTranslated: true,
    },
  ],
};

export const mergePotFile: PoFile = {
  filename: 'messages.pot',
  metadata: testPoFile.metadata,
  entries: [
    {
      id: 'incoming-welcome',
      msgctxt: 'dashboard',
      msgid: 'Welcome back',
      msgidPlural: null,
      msgstr: '',
      msgstrPlural: [],
      comments: {
        translator: 'Homepage heading',
      },
      isFuzzy: false,
      isObsolete: false,
      isTranslated: false,
    },
    {
      id: 'incoming-save',
      msgctxt: null,
      msgid: 'Save changes',
      msgidPlural: null,
      msgstr: '',
      msgstrPlural: [],
      comments: {
        extracted: 'Updated primary button label',
        reference: 'src/components/save.tsx:99',
        flag: 'php-format',
      },
      isFuzzy: false,
      isObsolete: false,
      isTranslated: false,
    },
    {
      id: 'incoming-new',
      msgctxt: null,
      msgid: 'New feature',
      msgidPlural: null,
      msgstr: '',
      msgstrPlural: [],
      comments: {},
      isFuzzy: false,
      isObsolete: false,
      isTranslated: false,
    },
  ],
};
